const panicData = [
{code:"0X80000",category:"SMC PANIC",cause:"It's the Proximity Flex Cable"},
{code:"0X140000",category:"SMC PANIC",cause:"It's the Charging Port & Power Button Flex or Barometer"},
{code:"0X180000",category:"SMC PANIC",cause:"It's the Prox Flex & Power Button Flex"},
{code:"0X20000",category:"SMC PANIC",cause:"It's a Sandwich Board Issue / Gyro"},
{code:"0X40000",category:"SMC PANIC",cause:"It's the Charging Port Flex"},
{code:"0X60000",category:"SMC PANIC",cause:"It's the Proximity Flex Cable"},
{code:"0X1800",category:"SMC PANIC",cause:"It's Both - Charging Port Flex & Prox Flex"},
{code:"0X10000",category:"SMC PANIC",cause:"It's the Power Button Flex"},
{code:"0X400",category:"SMC PANIC",cause:"Try to Reball Interposer"},
{code:"0X800",category:"SMC PANIC",cause:"It's the Charging Port Flex"},
{code:"0X1000",category:"SMC PANIC",cause:"It's the Proximity Flex Cable"},
{code:"0X194",category:"SMC PANIC",cause:"Problem with magnetometer or compass sensor"},
{code:"0X204",category:"SMC PANIC",cause:"Problem with humidity sensor or moisture detection"},
{code:"0X214",category:"SMC PANIC",cause:"Problem with pressure sensor or air pressure detection"},
{code:"0X164",category:"SMC PANIC",cause:"Problem with pressure sensor"},
{code:"0X174",category:"SMC PANIC",cause:"Problem with accelerometer or gravity sensor"},
{code:"0X184",category:"SMC PANIC",cause:"Problem with gyroscope or rotation sensor"},
{code:"0X134",category:"SMC PANIC",cause:"Problem with proximity sensor or light sensor"},
{code:"0X144",category:"SMC PANIC",cause:"Problem with ambient temperature sensor"},
{code:"0X154",category:"SMC PANIC",cause:"Problem with humidity sensor"},
{code:"0X104",category:"SMC PANIC",cause:"Problem with accelerometer or gravity sensor"},
{code:"0X114",category:"SMC PANIC",cause:"Problem with gyroscope or rotation sensor"},
{code:"0X124",category:"SMC PANIC",cause:"Problem with magnetometer or compass sensor"},
{code:"0X91",category:"SMC PANIC",cause:"Problem with network connectivity (Wi-Fi or cellular)"},
{code:"0X93",category:"SMC PANIC",cause:"Problem with gyroscope"},
{code:"0X94",category:"SMC PANIC",cause:"Problem with camera or imaging system"},
{code:"0X81",category:"SMC PANIC",cause:"Problem with camera or imaging system"},
{code:"0X83",category:"SMC PANIC",cause:"Problem with proximity sensor or screen auto-dimming"},
{code:"0X84",category:"SMC PANIC",cause:"Problem with vibration motor or haptic feedback"},
{code:"0X71",category:"SMC PANIC",cause:"Problem with audio or speaker system"},
{code:"0X73",category:"SMC PANIC",cause:"Problem with ambient light sensor / auto brightness"},
{code:"0X74",category:"SMC PANIC",cause:"Problem with speaker or audio output"},
{code:"0X61",category:"SMC PANIC",cause:"Problem with display (flickering or pixelation)"},
{code:"0X63",category:"SMC PANIC",cause:"Problem with accelerometer or motion sensor"},
{code:"0X64",category:"SMC PANIC",cause:"Problem with microphone or audio input"},
{code:"0X41",category:"SMC PANIC",cause:"Battery Data issue"},
{code:"0X42",category:"SMC PANIC",cause:"Thermal issue (overheating)"},
{code:"0X51",category:"SMC PANIC",cause:"Problem with security features or encryption"},
{code:"0X1D4",category:"SMC PANIC",cause:"Problem with gyroscope or orientation sensor"},
{code:"0X1E4",category:"SMC PANIC",cause:"Problem with barometer or altitude sensor"},
{code:"0X1F4",category:"SMC PANIC",cause:"Problem with thermometer or temperature sensor"},
{code:"0X1A4",category:"SMC PANIC",cause:"Problem with proximity sensor or light sensor"},
{code:"0X1B4",category:"SMC PANIC",cause:"Problem with ambient light sensor / auto brightness"},
{code:"0X1C4",category:"SMC PANIC",cause:"Problem with proximity sensor or screen auto-dimming"},
{code:"Dart-disp0 SMMU error",category:"SMC PANIC",cause:"Rear Camera"},
{code:"DPC error",category:"SMC PANIC",cause:"Hard disk and baseband circuit, crystal oscillator"},
{code:"Ememory",category:"SMC PANIC",cause:"Hard Disk or Hard Disk related circuit"},
{code:"Unknown sample rate on DAC",category:"SMC PANIC",cause:"Audio"},
{code:"Firmware fatal",category:"SMC PANIC",cause:"Firmware or underlying issue, or Power Button line"},
{code:"fed err (parity counter overflow, multi hit ICTAG)",category:"SMC PANIC",cause:"Hard Disk"},
{code:"Fatal coherency point error CP_com_NORM",category:"SMC PANIC",cause:"BUCK CPU power supply problem, CPU side inductance"},
{code:"Halt/Restart Timed out",category:"SMC PANIC",cause:"Tail Plug / Earphone Amplifier"},
{code:"Initproc exited -- exit",category:"SMC PANIC",cause:"Try software reflash or CPU reball"},
{code:"Invalid queue element linkage",category:"SMC PANIC",cause:"Hard Disk is welded or damaged"},
{code:"Initproc exited",category:"SMC PANIC",cause:"Main crystal failure"},
{code:"IOMFB int hander",category:"SMC PANIC",cause:"Screen or screen 0.8V power supply"},
{code:"Key hdr kind!=NEW",category:"SMC PANIC",cause:"Display IC"},
{code:"Kernel data abort",category:"SMC PANIC",cause:"Hard Disk / Board Layer"},
{code:"L2C",category:"SMC PANIC",cause:"WiFi / Audio Amplification"},
{code:"LLC Bus error from cpu3 (FAR)",category:"SMC PANIC",cause:"Abnormal communication between CPU and WiFi"},
{code:"LSU",category:"SMC PANIC",cause:"WiFi"},
{code:"LLC",category:"SMC PANIC",cause:"Baseband circuitry, possibly audio"},
{code:"lop_rinobuffer",category:"SMC PANIC",cause:"Audio related"},
{code:"Memorystatus_jetsam_thread",category:"SMC PANIC",cause:"Hard Disk"},
{code:"Mbuf_watchdog:12 waiters stuck",category:"SMC PANIC",cause:"Boot Cable / Tail Plug / Power Button"},
{code:"mbuf_watchdog:2 waiters stuck",category:"SMC PANIC",cause:"Hard Disk has bad sectors"},
{code:"Nvme",category:"SMC PANIC",cause:"Hard Disk"},
{code:"NO pulse on",category:"SMC PANIC",cause:"Vibration / Pulse (ring vibration)"},
{code:"Pmap_enter_pv unexpected PV head",category:"SMC PANIC",cause:"Earpiece row, small audio"},
{code:"PMP NMI FIQ",category:"SMC PANIC",cause:"CPU Power Supply"},
{code:"Pre, next",category:"SMC PANIC",cause:"Main Crystal Failure"},
{code:"Reset sequence did not finish within 5000ms",category:"SMC PANIC",cause:"Abnormal communication between CPU and WiFi"},
{code:"Rtunref Bad refcnt",category:"SMC PANIC",cause:"Hard Disk"},
{code:"RTBuddy (AOP) setmanagedGated",category:"SMC PANIC",cause:"Battery Holder"},
{code:"Releasing non_exclusive",category:"SMC PANIC",cause:"CPU Inductor"},
{code:"Sep memory protection module error",category:"SMC PANIC",cause:"EEPROM (screen / CPU / Baseband)"},
{code:"SEP ROM",category:"SMC PANIC",cause:"Fingerprint ROM / Logic Chip"},
{code:"Sep ROM boot Panic",category:"SMC PANIC",cause:"EEPROM CPU, Resistors or CPU"},
{code:"SEP Panic::dxio/I2C: 0X100007785",category:"SMC PANIC",cause:"EEPROM CPU, Resistors or CPU"},
{code:"SEP Panic::sars/sars: 0X10000f439",category:"SMC PANIC",cause:"EEPROM CPU, Resistors or CPU"},
{code:"SMC DATA ABORT",category:"SMC PANIC",cause:"Abnormal CPU Communication"},
{code:"Stacks+routined-(2019 01 29)",category:"SMC PANIC",cause:"iPad - usually caused by battery screw post being too long (Special iPad)"},
{code:"sks request timeout",category:"SMC PANIC",cause:"CPU to logic code fragment line / EEPROM"},
{code:"Sleep/wake hang detected",category:"SMC PANIC",cause:"Battery, Audio CPU powered"},
{code:"SEP panic::daio/i2c",category:"SMC PANIC",cause:"Down antenna problem"},
{code:"SMC PANIC",category:"SMC PANIC",cause:"CPU power supply - check inductance"},
{code:"Spmi timeout",category:"SMC PANIC",cause:"Audio related"},
{code:"SEP Panic sars/sars",category:"SMC PANIC",cause:"Earpiece row, small audio"},
{code:"Timeout waiting for stop to IDLE on EP",category:"SMC PANIC",cause:"Screen"},
{code:"Trying to change a collection in the registry",category:"SMC PANIC",cause:"Just flash"},
{code:"Void applesynopsysMIPID",category:"SMC PANIC",cause:"SI Controller"},
{code:"0XD4",category:"SMC PANIC",cause:"Problem with ambient temperature sensor"},
{code:"0XE4",category:"SMC PANIC",cause:"Problem with humidity sensor"},
{code:"0XF4",category:"SMC PANIC",cause:"Problem with pressure sensor"},
{code:"0XA4",category:"SMC PANIC",cause:"Problem with touch screen or digitizer"},
{code:"0XB4",category:"SMC PANIC",cause:"Problem with SIM card or cellular connectivity"},
{code:"0XC4",category:"SMC PANIC",cause:"Problem with fingerprint sensor or biometric auth"},
{code:"0XD1",category:"SMC PANIC",cause:"Problem with vibration motor or haptic feedback"},
{code:"0XE1",category:"SMC PANIC",cause:"Problem with ambient light sensor or proximity sensor"},
{code:"0XF1",category:"SMC PANIC",cause:"Problem with gyroscope or accelerometer"},
{code:"0XA1",category:"SMC PANIC",cause:"Problem with GPS or location services"},
{code:"0XB1",category:"SMC PANIC",cause:"Problem with Touch ID or Face ID functionality"},
{code:"0XC1",category:"SMC PANIC",cause:"Problem with microphone or audio input"},
{code:"0Xa1",category:"SMC PANIC",cause:"Battery Communications"},
{code:"0XD00000",category:"SMC PANIC",cause:"Sensor-related (accelerometer, gyroscope, proximity, ambient light)"},
{code:"0XF00000",category:"SMC PANIC",cause:"Miscellaneous hardware issue (buttons, connectors, hardware integrity)"},
{code:"0XA00000",category:"SMC PANIC",cause:"Battery-related issue"},
{code:"0XB00000",category:"SMC PANIC",cause:"Audio-related issue (speakers, mic, headphone jack, output)"},
{code:"0X1C0000",category:"SMC PANIC",cause:"Charging Port & Power Button Flex & Prox Flex"},
{code:"0XC0000",category:"SMC PANIC",cause:"Prox Flex & Charging Port Flex"},
{code:"0XC00000",category:"SMC PANIC",cause:"Security feature issue (Touch ID / Face ID / Secure Enclave)"},
{code:"0X700000",category:"SMC PANIC",cause:"Charging flex & wireless charging flex"},
{code:"0X800000",category:"SMC PANIC",cause:"Software-related issue (17pro max) wireless flex"},
{code:"0X400000",category:"SMC PANIC",cause:"Wireless Charging Flex (back glass)"},
{code:"0X500000",category:"SMC PANIC",cause:"Battery Communications"},
{code:"0X600000",category:"SMC PANIC",cause:"Wireless charging flex & proximity flex"},
{code:"0X100000",category:"SMC PANIC",cause:"Power Button Flex / Charging Port Flex"},
{code:"0X200000",category:"SMC PANIC",cause:"Proximity Flex Cable"},
{code:"0X300000",category:"SMC PANIC",cause:"Proximity Flex Cable / camera issue (autofocus, image stabilization)"},
{code:"TT1P TT2P",category:"SMC PANIC",cause:"Screen"},
{code:"TG0B",category:"SMC PANIC",cause:"Battery - No Data"},
{code:"TG0V TTSA",category:"SMC PANIC",cause:"Charging Port Flex"},
{code:"Prs0",category:"SMC PANIC",cause:"Charging Port Flex / U7400"},
{code:"MIC1",category:"SMC PANIC",cause:"Charging Port Flex"},
{code:"MIC2",category:"SMC PANIC",cause:"Power Key Flex / SpringBoard"},
{code:"600seconds",category:"SMC PANIC",cause:"Hard Disk (Nand)"},
{code:"Systick watchdog",category:"SMC PANIC",cause:"Big Audio"},
{code:"Systick watchdog2 not pet",category:"SMC PANIC",cause:"Gyro"},
{code:"No pulse on",category:"SMC PANIC",cause:"Big Audio / Front SP / Vibration"},
{code:"AMCC ERROR",category:"SMC PANIC",cause:"Front SP"},
{code:"AOP PANIC (7P)",category:"SMC PANIC",cause:"Proximity sensing / rear MIC 7P / power-on flex / fingerprint"},
{code:"AOP PANIC (general)",category:"SMC PANIC",cause:"Big Audio / Screen Failure"},
{code:"AOP DATA ABORT",category:"SMC PANIC",cause:"Hard Drive first, then check CPU solder joint"},
{code:"K2-bosch control",category:"SMC PANIC",cause:"Vibrator"},
{code:"PressureController.cpp:280",category:"SMC PANIC",cause:"Check L3302 layer / rear camera / distance sensor / rear MIC 7P boot cable / fingerprint"},
{code:"Attempting to forcibly halt CPU",category:"SMC PANIC",cause:"CPU Solder Joint"},
{code:"AMCC Error",category:"SMC PANIC",cause:"Light-sensitive"},
{code:"AppleBCMWLAN",category:"SMC PANIC",cause:"WiFi Bluetooth"},
{code:"Anc-postnand.c1260 assert failed link",category:"SMC PANIC",cause:"Nand problem"},
{code:"AGXK AGXAccelerator",category:"SMC PANIC",cause:"Gyroscope Accelerator Coprocessor"},
{code:"AppleSOC hot hot hot",category:"SMC PANIC",cause:"WiFi / Big Audio / CPU reflow needed"},
{code:"ANS",category:"SMC PANIC",cause:"Hard Disk circuit or board layer"},
{code:"ANS2",category:"SMC PANIC",cause:"Hard Disk circuit or board layer"},
{code:"AOP NMI POWER",category:"SMC PANIC",cause:"Front Cable / Power Button Cable"},
{code:"Apple PMGR",category:"SMC PANIC",cause:"Battery"},
{code:"Apple PPM",category:"SMC PANIC",cause:"Charging IC / Battery Conversion"},
{code:"apcie (wlan)",category:"SMC PANIC",cause:"WiFi Module"},
{code:"A freed zone element has been modified",category:"SMC PANIC",cause:"CPU Solder Joint"},
{code:"A kext releasing",category:"SMC PANIC",cause:"First consider CPU inductance"},
{code:"apcie(0:s3e)",category:"SMC PANIC",cause:"Hard Disk"},
{code:"AppleHIDTransportProtocol",category:"SMC PANIC",cause:"Screen"},
{code:"APFS_TREE",category:"SMC PANIC",cause:"Hard Disk (Nand)"},
{code:"Bad tallq elm",category:"SMC PANIC",cause:"Main Crystal Oscillator / Wide-Angle Camera / Screen"},
{code:"BASEBAND cluster_push",category:"SMC PANIC",cause:"Baseband part"},
{code:"err:expectedNULL",category:"SMC PANIC",cause:"Load software (reflash)"},
{code:"Coherency point error",category:"SMC PANIC",cause:"Check the rear camera"},
{code:"CP_COM_NORM REQUEST",category:"SMC PANIC",cause:"CPU Hard Disk / Camera Circuit"},
{code:"CSL AUDIO",category:"SMC PANIC",cause:"Audio related"},
{code:"SCMto",category:"AOP",cause:"Vibration"},
{code:"Systick wacthdog",category:"AOP",cause:"Big audio"},
{code:"Systick wacthdog2 not pet",category:"AOP",cause:"Gyro"},
{code:"no pluse on",category:"AOP",cause:"Big audio sp/vibration/front sp"},
{code:"AMCC  ERROR",category:"AOP",cause:"Front speker"},
{code:"AOP PANIC(7P)",category:"AOP",cause:"Proximity sensor flrx rear( mic 7P) ON/OFF Flex/finger print"},
{code:"(AOP PANIC)",category:"AOP",cause:"BIG AUDIO screen failure"},
{code:"AOP DATA ABORT",category:"AOP",cause:"First nand/ (cpu)"},
{code:"k2-bosch control",category:"AOP",cause:"Vibration"},
{code:"pressureController.cpp:280",category:"AOP",cause:"Layer /rear camera/check distance sensor (7p) rear mic boot cable /check fimger print"},
{code:"TT1P TT2P",category:"WATCHDOG",cause:"SCREEN"},
{code:"TG0B",category:"WATCHDOG",cause:"BATTERY NO DATA"},
{code:"TP3R",category:"WATCHDOG",cause:"NTC PROBLEM"},
{code:"TP2A /TP3R /TP4H",category:"WATCHDOG",cause:"BATTERY/SCREEN"},
{code:"TP2C",category:"WATCHDOG",cause:"BATTERY/SCREEN"},
{code:"TG0V/ TTSA",category:"WATCHDOG",cause:"Charging flex cable"},
{code:"Prs0",category:"WATCHDOG",cause:"Charging flex cable"},
{code:"mic1",category:"WATCHDOG",cause:"Charging flex cable"},
{code:"mic2",category:"WATCHDOG",cause:"Power flex/flash light flax"},
{code:"spring board",category:"WATCHDOG",cause:"First restore/reball sandwich board"},
{code:"600seconds",category:"WATCHDOG",cause:"NAND (HARD DISK)"},
{code:"without the above code",category:"WATCHDOG",cause:"U2 priorty(tristar-hydra)"},
{code:"Attemping to forcibly halt CPU",category:"SMC PANIC",cause:"CPU Solder Joint"},
{code:"Anc-postnand.c1260 asser failed link",category:"SMC PANIC",cause:"Nand problem"},
{code:"AAPLE PMGR",category:"SMC PANIC",cause:"Battery"},
{code:"apcie(wlan)",category:"SMC PANIC",cause:"WIFI /LAYER"},
{code:"a freed zone elements has been modified",category:"SMC PANIC",cause:"CPU REBALL"},
{code:"appleHIDTrabsport ocol",category:"SMC PANIC",cause:"SCREEN"},
{code:"busy timeout",category:"SMC PANIC",cause:"Audio/PMIC"},
{code:"baseband",category:"SMC PANIC",cause:"Layer baseband cpu and circit"},
{code:"cluster_pusherr:expactedNULL",category:"SMC PANIC",cause:"SOFTWARE LOAD"},
{code:"CLS AUDIO",category:"SMC PANIC",cause:"Audio related"},
{code:"CAN Snoop",category:"SMC PANIC",cause:"Ply stub"},
{code:"DCP PANIC",category:"SMC PANIC",cause:"Charging flex"},
{code:"DCP err UNKOWN:MULTIPLE)on..",category:"SMC PANIC",cause:"PMU/BUCK COIL /CPU"},
{code:"DPC err",category:"SMC PANIC",cause:"Namd bb cristal"},
{code:"enableHalogen;3833 unknow samle rate on..",category:"SMC PANIC",cause:"Audio"},
{code:"fed err (parity counter overflow multi hit ICTAG)",category:"SMC PANIC",cause:"Nand problem"},
{code:"Halt /restart Time out",category:"SMC PANIC",cause:"Tail plug /earphone Amplifier"},
{code:"Iokit",category:"SMC PANIC",cause:"Iokit"},
{code:"initproc exited --exit",category:"SMC PANIC",cause:"First software/CPU Reball"},
{code:"initproc-exited",category:"SMC PANIC",cause:"Main crystal"},
{code:"Key hdr kind'=NEW",category:"SMC PANIC",cause:"Display Ic"},
{code:"LLC Bus error from cpu 3: FAR",category:"SMC PANIC",cause:"Layer wifi to cpu conections"},
{code:"menorystaus_jetsam_thread",category:"SMC PANIC",cause:"Nand problem"},
{code:"mMbuf_wacthdog:12 waiters stuck",category:"SMC PANIC",cause:"On/off flex/charging flex cable/"},
{code:"mubf_wacthdog:2waiters stuck",category:"SMC PANIC",cause:"Nand problem"},
{code:"Pmap-enter_ov.unesxpected pv head",category:"SMC PANIC",cause:"Earpice section small audio ic"},
{code:"pre,next",category:"SMC PANIC",cause:"Main crystal"},
{code:"reset sequence did not finish witin S00ms",category:"SMC PANIC",cause:"Abnormal communicatinon between COU &WIFI"},
{code:"Rtunerf Bad refcnt",category:"SMC PANIC",cause:"Nand problem"},
{code:"Relesing non_exclusive",category:"SMC PANIC",cause:"CPU REBALL"},
{code:"Stack+routined_2019 01 29",category:"SMC PANIC",cause:"The ipad is mostly caused by the battry screw post being long (special Ipad)"},
{code:"SEP Panic ::sars/|sars 0x10000f439",category:"SMC PANIC",cause:"CPU /EEPROM RESISTOR OR CPU"},
{code:"SEP Panic :dxio/|i2c0x100007785",category:"SMC PANIC",cause:"CPU /EEPROM RESISTOR OR CPU"},
{code:"sep memory protection moddule error",category:"SMC PANIC",cause:"EEPROM (SCREEN/CPU/BASEBAND)"},
{code:"Void appleseynopsysMIPIDSIController",category:"SMC PANIC",cause:"Front cable"},
{code:"WTD timeout",category:"SMC PANIC",cause:"Battery /battery connector"},
{code:"WKDMD ERROR code 0x2",category:"SMC PANIC",cause:"Flashig error /nand problem"}
];

